steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "function-2",
        "--entry-point=hello_http",
        "--region=us-central1",
        "--trigger-http",
        "--runtime=python312",
        "--source=function-2",
      ]
